
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 24 19:56:13 CET 2020
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 5;
  public static final int CHAR = 46;
  public static final int CONST = 14;
  public static final int EQUALS = 25;
  public static final int GRT = 27;
  public static final int SEMICOLN = 7;
  public static final int CASE = 36;
  public static final int CONTINUE = 40;
  public static final int LPAREN = 10;
  public static final int DECR = 24;
  public static final int LESS = 29;
  public static final int RPAREN = 11;
  public static final int AND = 31;
  public static final int NEQUALS = 26;
  public static final int LESSEQUAL = 30;
  public static final int OR = 32;
  public static final int QMARK = 42;
  public static final int COMMA = 9;
  public static final int INC = 23;
  public static final int DIV = 21;
  public static final int NUM = 44;
  public static final int IF = 33;
  public static final int BOOLEAN = 45;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int RBRACKET = 6;
  public static final int EQUAL = 8;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 20;
  public static final int ADD = 18;
  public static final int MOD = 22;
  public static final int IDENT = 43;
  public static final int BREAK = 39;
  public static final int VOID = 4;
  public static final int GRTEQUAL = 28;
  public static final int SWITCH = 35;
  public static final int LBRACE = 12;
  public static final int ELSE = 34;
  public static final int READ = 17;
  public static final int WHILE = 38;
  public static final int RBRACE = 13;
  public static final int DDOTS = 41;
  public static final int SUB = 19;
  public static final int DO = 37;
  public static final int PRINT = 16;
}

