
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 24 18:22:28 CET 2020
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 20;
  public static final int CHAR = 46;
  public static final int CONST = 33;
  public static final int EQUALS = 10;
  public static final int GRT = 12;
  public static final int SEMICOLN = 23;
  public static final int CASE = 38;
  public static final int LPAREN = 25;
  public static final int CONTINUE = 2;
  public static final int DECR = 19;
  public static final int LESS = 14;
  public static final int RPAREN = 26;
  public static final int AND = 16;
  public static final int NEQUALS = 11;
  public static final int LESSEQUAL = 15;
  public static final int OR = 17;
  public static final int QMARK = 40;
  public static final int COMMA = 24;
  public static final int INC = 18;
  public static final int DIV = 8;
  public static final int NUM = 44;
  public static final int IF = 34;
  public static final int BOOLEAN = 45;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int RBRACKET = 21;
  public static final int EQUAL = 22;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int PROGRAM = 29;
  public static final int MUL = 7;
  public static final int ADD = 5;
  public static final int MOD = 9;
  public static final int IDENT = 43;
  public static final int BREAK = 30;
  public static final int VOID = 4;
  public static final int GRTEQUAL = 13;
  public static final int SWITCH = 37;
  public static final int LBRACE = 27;
  public static final int ELSE = 32;
  public static final int READ = 36;
  public static final int WHILE = 42;
  public static final int RBRACE = 28;
  public static final int DDOTS = 39;
  public static final int SUB = 6;
  public static final int DO = 41;
  public static final int PRINT = 31;
}

